### PR TITLE
Bypass CSRF check.

### LINKED ISSUE #28: Twitter SSO fails immediately
with the following message

```
Internal Error.
Oops! Looks like something went wrong!

/auth/twitter

Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
```

### LINKED ISSUE #29: Twitter OAuth changes
Re-opening here from https://github.com/NodeBB/NodeBB/issues/6719

> `/admin/plugins/sso-twitter` links to a deprecated (as of July '18) URL: https://apps.twitter.com/
>
>> As of July 2018, you must [apply for a Twitter developer account](https://developer.twitter.com/en/apply/user) and be approved before you may create new apps. Once approved, you will be able to create new apps from developer.twitter.com.
>>
>> For the near future, you can continue to manage existing apps here on apps.twitter.com. However, we will soon retire this site and consolidate all developer tools, API access, and app management within the developer portal at developer.twitter.com. You will be able to access and manage existing apps through that portal when we retire this site.

### LINKED ISSUE #30: broken on community.nodebb.org
Not sure if its related to the other issues

It redirects back to https://community.nodebb.org/auth/twitter/callback?oauth_token=<token>&oauth_verifier=<verifier>
And shows a nodebb error screen

```
Internal Error.
Oops! Looks like something went wrong!

/auth/twitter/callback

We were unable to log you in, likely due to an expired session. Please try again
```

### PR DESCRIPTION
**Pull request by BenLubar**
See inline comment for why this is safe.

Fixes #28. Fixes #29. Fixes #30.

### CODE REVIEW

**Comment by julianlam** [comment]
Odd, because _core_ is what adds `/auth/:name/callback` to the router, not the plugins. How come this duplication is necessary to resolve callback url errors?

**Comment by BenLubar** [comment]
Core checks for CSRF by assuming that all SSO plugins use OAuth2 and sending the CSRF token as the `state` parameter. Twitter *doesn't* support OAuth2 for SSO, so the `state` parameter isn't sent to or from Twitter.

**Comment by BenLubar** [comment]
Basically, this code runs before the core SSO code and tricks it into thinking the CSRF token was provided. The `passport-twitter` module does its own CSRF checking, so this isn't a security risk.

It's live on https://what.thedailywtf.com/ if you want to try it out.

**Comment by julianlam** [comment]
Understood, this looks fine to me :+1: though I will likely add your explanation inline via comment

**Comment by julianlam** [comment]
v2.5.7

**Pull request merged**
